project:
  type: website
  output-dir: docs

website:
  title: "Matthew C. Nowlin"
  navbar:
    left:
      - href: index.qmd
        text: "{{< fa solid house >}}"
      - research.qmd
      - teaching.qmd
    right:
      - icon: envelope
        href: mailto:nowlinmc@cofc.edu
      - href: https://www.dropbox.com/s/nm5uajd5txnhg6v/nowlin-cv-short.pdf?dl=0
        text: "{{< ai cv >}}"
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?user=xu7Y7_QAAAAJ&hl=en
      - text: "{{< fa brands orcid >}}"
        href: https://orcid.org/0000-0002-0513-3756
      - text: "{{< ai osf >}}"
        href: https://osf.io/j7nbz/

  page-footer:
    left: |
        <span class="faux-block">{{< fa copyright >}} 2023, Matthew C. Nowlin</span>
    right:  |
      <span class="faux-block">Made using {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span> <br>
      <span class="faux-block">View the source code [{{< fa brands github >}} GitHub](https://github.com/mnowlin/nowlin-quarto-website)</span>

format:
  html:
    theme: cosmo
    css: styles.css
    mainfont: EB Garamond
    toc: true



