---
title: ""
---

# Public Attribution of Responsibility for Disaster Preparedness across Three Levels of Government and the Public: Lessons from a Survey of Residents of the U.S. South Atlantic and Gulf Coast Areas

<a href="https://academic.oup.com/publius/article-abstract/51/2/212/5943216?redirectedFrom=fulltext"> <span class="badge bg-primary">Published version</span></a >

## Abstract 
Using survey data collected from residents of counties along the South Atlantic and Gulf Coasts of the United States, we use innovative compositional data analysis techniques to examine individuals’ assignment of responsibility for hurricane preparedness across federal, state, and local officials as well as among household residents and their community. We find that the public assigns limited responsibility for hurricane preparedness to governments. Rather, respondents, especially conservatives and those with low trust in government, view individuals themselves as responsible for preparedness. Our results emphasize the role of ideology and the individualistic culture of American politics. These results also have implications for scholars who study individual attribution responsibility in multi-level systems and who may assume that individuals will assign responsibility to one of the various levels of government; however, focusing on disaster preparation in particular, our study shows that a significant number of individuals may not assign responsibility to government at any level.

## BibTex citation 

```bibtex
@article{wehdePublicAttributionResponsibility2021,
  title = {Public {{Attribution}} of {{Responsibility}} for {{Disaster Preparedness}} across {{Three Levels}} of {{Government}} and the {{Public}}: {{Lessons}} from a {{Survey}} of {{Residents}} of the {{U}}.{{S}}. {{South Atlantic}} and {{Gulf Coast}}},
  shorttitle = {Public {{Attribution}} of {{Responsibility}} for {{Disaster Preparedness}} across {{Three Levels}} of {{Government}} and the {{Public}}},
  author = {Wehde, Wesley and Nowlin, Matthew C.},
  year = {2021},
  journal = {Publius: The Journal of Federalism},
  volume = {51},
  number = {2},
  pages = {212--237},
  doi = {10.1093/publius/pjaa037}
}
```


